- name: Print a Message
  hosts: web
  tasks:
  - name: print a message from Ansible server
    ansible.builtin.debug:
      msg: Hi NodeServer, You are printing this Message from the Ansible Playbook.
