- name: Printing Variables based on preference
  hosts: local
  connection: local
  vars: #  PLAY level variables
    WLevel: Play
  vars_prompt:
  - name: Wlevel
    prompt: Please enter Wlevel name
    private: false # it is not confidential information
  vars_files:
  - env-var.yaml #  FILE level variables
  tasks:
  - name: Priniting Variables
    vars:
      Wlevel: Task #  TASK level variables
    ansible.builtin.debug:
      msg: Hello I'm printing msg from {{Wlevel}}
    