- name: Install Nginx
  hosts: web
  become: yes
  tasks:
  - name: Install Nginx if its RHEL
    ansible.builtin.dnf:
      name: Nginx
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Install Nginx if its Ubuntu
    ansible.builtin.apt:
      name: Nginx
      state: installed
    when: ansible_os_family == "Debian"