- name: Filters or functions
  hosts: local
  connection: local
  tasks:
  - name: Printing the values using Filters
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Anudeep') }}"
  
  - name: convert string to list
    vars:
      persons: "Anudeep, Gummy, David" #String
    ansible.builtin.debug:
      msg: "Persons are: {{ persons | split(',') }}"