- name: Filters or functions
  hosts: local
  connection: local
  tasks:
  - name: Printing the values using Filters
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Anudeep') }}"
  
  - name: convert string to list
    vars:
      persons: "Anudeep, Gummy, David" #String
    ansible.builtin.debug:
      msg: "Persons are: {{ persons | split(',') }}"

  - name: convert map into list
    vars:
      course:
        learn: ansible
        duration: 10hrs
        trainee: Anudeep
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"
    
  - name: convert list into map
    vars:
      course:
      - {'key': 'learn', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'trainee', 'value': 'Anudeep'}
    ansible.builtin.debug:
      msg: "Course info: {{ course | items2dict }}"

  - name: convert upper to lower
    tags:
    - uppertolower
    vars:
      name: "Anudeep"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: convert lower to upper
    tags:
    - lowertoupper
    vars:
      name: "Anudeep"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: print min and max
    vars:
      numbers: [134,350,6257,2787,9787,83937]
    ansible.builtin.debug:
      msg: "Min is: {{ numbers | min }}, Max is: {{ numbers | max }}"

  - name: check ipaddress is valid or not
    vars:
      ip: "35849.1392832.3423"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"