- name: Filters or functions
  hosts: local
  connection: local
  tasks:
  - name: Printing the values using Filters
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Anudeep') }}"
  
  - name: convert string to list
    vars:
      persons: "Anudeep, Gummy, David" #String
    ansible.builtin.debug:
      msg: "Persons are: {{ persons | split(',') }}"

  - name: convert map into list
    vars:
      course:
        learn: ansible
        duration: 10hrs
        trainee: Anudeep
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"
    
  - name: convert list into map
    vars:
      course:
      - {'key': 'learn', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'trainee', 'value': 'Anudeep'}
    ansible.builtin.debug:
      msg: "Course info: {{ course | items2dict }}"