- name: Differnce Between Shell and Command
  hosts: local
  connection: local
  tasks:
  - name: Executing
    #ansible.builtin.command: ls -ltr > /tmp/output.txt
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
  
  - name: Executing
    #ansible.builtin.command: ls -ltr > /tmp/output.txt
    #ansible.builtin.command: lsss -ltrssfff # exit status 0
    ansible.builtin.shell: ls -ltr # exit status 1
    register: command_result

  - name: Print the output
    ansible.builtin.debug:
      msg: "{{ command_result }}"