---
- name: Create EC2 Instances (frontend, backend, mysql)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: us-east-1
    instance_type: t3.micro
    key_name: learningdevops
    security_group: default

    image_id: ami-0c02fb55956c7d316
  tasks:

    - name: Create frontend instance
      amazon.aws.ec2_instance:
        name: frontend
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        region: "{{ region }}"
        security_group: "{{ security_group }}"
        wait: true

    - name: Create backend instance
      amazon.aws.ec2_instance:
        name: backend
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        region: "{{ region }}"
        security_group: "{{ security_group }}"
        wait: true

    - name: Create mysql instance
      amazon.aws.ec2_instance:
        name: mysql
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        region: "{{ region }}"
        security_group: "{{ security_group }}"
        wait: true
